version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ${HOST_STATIC_DIR}:/static
    links:
      - db
    ports:
      - "8000:8000"
    depends_on:
      - db
