ASSETS_DIR := ./vendor/js/

sync-js:
	mkdir -p $(ASSETS_DIR)
	cp node_modules/jquery/jquery.min.js* $(ASSETS_DIR)
	cp node_modules/popper.js/dist/umd/popper.min.js* $(ASSETS_DIR)
	cp node_modules/bootstrap/dist/js/bootstrap.min.js* $(ASSETS_DIR)
