# Generated by Django 2.2.7 on 2019-12-06 07:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardEquipmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('manufacturer', models.CharField(max_length=256)),
                ('manufacture_date_fmt', models.CharField(choices=[('Y', 'Year'), ('YM', 'Year-Month'), ('YMD', 'Year-Month-Date')], default='YMD', max_length=8)),
                ('manufacture_date', models.DateField()),
                ('model', models.CharField(max_length=256)),
                ('purpose', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('spec', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Specification and performance')),
                ('location', models.CharField(max_length=256)),
                ('photos', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('related_link', models.URLField(blank=True, null=True)),
                ('extra', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
