# Generated by Django 2.2.7 on 2019-12-06 07:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191205_0154'),
        ('wagtailimages', '0001_squashed_0021'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardequipmentpage',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.Person'),
        ),
        migrations.CreateModel(
            name='EquipmentPhotoRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('equipment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_photo_relationship', to='equipment.StandardEquipmentPage')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_equipment_relationship', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
