# Generated by Django 2.2.7 on 2019-12-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardequipmentpage',
            name='photos',
        ),
    ]
