# Generated by Django 2.2.7 on 2019-11-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sectionpage'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPeopleRelationship',
            new_name='BlogPersonRelationship',
        ),
        migrations.RenameField(
            model_name='blogpersonrelationship',
            old_name='people',
            new_name='person',
        ),
    ]
