# Generated by Django 2.2.7 on 2019-12-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191204_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tweetindexpage',
            old_name='introduction',
            new_name='description',
        ),
    ]
