# Generated by Django 2.2.7 on 2019-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191204_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='tweetindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='tweetindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
    ]
