# Generated by Django 2.2.7 on 2019-12-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191211_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetPersonRelationship',
        ),
    ]
