# Generated by Django 2.2.7 on 2019-11-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminarpage',
            old_name='start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='seminarpage',
            name='end',
        ),
        migrations.AddField(
            model_name='seminarpage',
            name='place',
            field=models.CharField(default='Nowhere', max_length=250),
            preserve_default=False,
        ),
    ]
