# Generated by Django 2.2.7 on 2019-12-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191204_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsindexpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='seminarsindexpage',
            old_name='introduction',
            new_name='description',
        ),
    ]
