# Generated by Django 2.2.7 on 2019-11-24 03:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('event', '0002_auto_20191124_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventIndexPage',
            new_name='EventsIndexPage',
        ),
        migrations.RenameModel(
            old_name='SeminarIndexPage',
            new_name='SeminarsIndexPage',
        ),
    ]
