# Generated by Django 2.2.7 on 2019-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191205_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='eventsindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarsindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='seminarsindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='seminarsindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
    ]
