# Generated by Django 2.2.7 on 2019-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20191211_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardeventpage',
            name='abstract_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardeventpage',
            name='our_speakers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
