# Generated by Django 2.2.7 on 2019-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20191215_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsindexpage',
            name='view_type',
            field=models.CharField(choices=[('list', 'List'), ('table', 'Table')], default='list', max_length=64),
        ),
    ]
