# Generated by Django 2.2.7 on 2019-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faqindexpage_faqpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
