# Generated by Django 2.2.7 on 2019-11-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0004_homeslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='title',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
