# Generated by Django 2.2.7 on 2019-11-20 11:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191120_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHomeSliderRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('homeslider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeslider_home_relationship', to='home.HomeSlider')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_homeslider_relationship', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
