# Generated by Django 2.2.7 on 2019-12-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191204_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqindexpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='faqpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sectionpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='standardpage',
            old_name='introduction',
            new_name='description',
        ),
    ]
