# Generated by Django 2.2.7 on 2019-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191122_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Home slider', 'verbose_name_plural': 'Home sliders'},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
