# Generated by Django 2.2.7 on 2019-11-24 09:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191124_0957'),
        ('publication', '0011_auto_20191124_0658'),
        ('home', '0011_sectionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPeopleIndexRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='peopleindex_person_relationship', to='home.PeopleIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='PeopleRelationship',
        ),
        migrations.AddField(
            model_name='personpeopleindexrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_peopleindex_relationship', to='home.Person'),
        ),
    ]
