# Generated by Django 2.2.7 on 2019-12-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='title_ko',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Korean)'),
        ),
    ]
