# Generated by Django 2.2.7 on 2019-12-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191210_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpage',
            name='body',
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
    ]
