# Generated by Django 2.2.7 on 2019-12-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepage_news_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqindexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='careersindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='careersindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='faqindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleriesindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='galleriesindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopleindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='peopleindexpage',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='peopleindexpage',
            name='title_ko',
            field=models.CharField(default='Unknown Korean Title', max_length=255, verbose_name='Title (Korean)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careersindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='faqindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='galleriesindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Description (English)'),
        ),
    ]
