# Generated by Django 2.2.7 on 2019-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profilepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleindexpage',
            name='view_type',
            field=models.CharField(choices=[('list', 'List'), ('simple', 'Simple')], default='list', max_length=64),
        ),
    ]
