# Generated by Django 2.2.7 on 2019-12-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papersindexpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='presentationsindexpage',
            old_name='introduction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='thesesindexpage',
            old_name='introduction',
            new_name='description',
        ),
    ]
