# Generated by Django 2.2.7 on 2019-11-16 03:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='presentor',
            field=models.CharField(default='Unknown', max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PresentationPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publication.PresentationPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_presentationpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publication.PresentationPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
