# Generated by Django 2.2.7 on 2019-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20191204_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='presentationpage',
            name='collaboration',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
