# Generated by Django 2.2.7 on 2019-11-17 02:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_people'),
        ('publication', '0002_auto_20191116_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationpage',
            name='presentor',
        ),
        migrations.CreateModel(
            name='PresentationPeopleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_person_relationship', to='publication.PresentationPage')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_presentation_relationship', to='home.People')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
