# Generated by Django 2.2.7 on 2019-12-04 14:29

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20191204_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='paperpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='paperpage',
            name='volume',
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='abstract',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='authors',
            field=models.TextField(),
        ),
    ]
