# Generated by Django 2.2.7 on 2019-12-05 01:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20191204_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='doi',
        ),
        migrations.AddField(
            model_name='paperpage',
            name='bibtex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='doi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='extra',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='extra',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesispage',
            name='extra',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='abstract',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='meeting',
            field=models.CharField(default='Unknown', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thesispage',
            name='abstract',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
