# Generated by Django 2.2.7 on 2019-12-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20191205_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesispersonrelationship',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thesispersonrelationship',
            name='page',
        ),
        migrations.DeleteModel(
            name='PaperPersonRelationship',
        ),
        migrations.DeleteModel(
            name='ThesisPersonRelationship',
        ),
    ]
