# Generated by Django 2.2.7 on 2019-11-17 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('publication', '0006_publicationindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationIndexPage',
            new_name='PresentationsIndexPage',
        ),
        migrations.RenameModel(
            old_name='PresentationIndexPage',
            new_name='PublicationsIndexPage',
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='date',
            field=models.DateField(verbose_name='Presentation date'),
        ),
    ]
