# Generated by Django 2.2.7 on 2019-12-05 02:54

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_auto_20191205_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publication.PaperPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
