# Generated by Django 2.2.7 on 2019-12-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_auto_20191205_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpage',
            name='refinfo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Volume, Issue, Page'),
        ),
    ]
