# Generated by Django 2.2.7 on 2019-11-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0003_people'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('publication', '0008_auto_20191117_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperPeopleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ArticlesIndexPage',
            new_name='PapersIndexPage',
        ),
        migrations.RemoveField(
            model_name='articlepeoplerelationship',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articlepeoplerelationship',
            name='people',
        ),
        migrations.RenameModel(
            old_name='ArticlePage',
            new_name='PaperPage',
        ),
        migrations.DeleteModel(
            name='ArticlePageTag',
        ),
        migrations.DeleteModel(
            name='ArticlePeopleRelationship',
        ),
        migrations.AddField(
            model_name='paperpeoplerelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_person_relationship', to='publication.PaperPage'),
        ),
        migrations.AddField(
            model_name='paperpeoplerelationship',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_paper_relationship', to='home.People'),
        ),
        migrations.AddField(
            model_name='paperpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publication.PaperPage'),
        ),
        migrations.AddField(
            model_name='paperpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_paperpagetag_items', to='taggit.Tag'),
        ),
    ]
