# Generated by Django 2.2.7 on 2019-12-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_auto_20191205_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperpage',
            old_name='url',
            new_name='permalink',
        ),
    ]
