# Generated by Django 2.2.7 on 2019-11-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sectionpage'),
        ('publication', '0010_auto_20191124_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesispage',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.People'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publication.Collaboration'),
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publication.Journal'),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publication.Collaboration'),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publication.Meeting'),
        ),
    ]
