# Generated by Django 2.2.7 on 2019-11-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191124_0957'),
        ('publication', '0011_auto_20191124_0658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaperPeopleRelationship',
            new_name='PaperPersonRelationship',
        ),
        migrations.RenameModel(
            old_name='PresentationPeopleRelationship',
            new_name='PresentationPersonRelationship',
        ),
        migrations.RenameModel(
            old_name='ThesisPeopleRelationship',
            new_name='ThesisPersonRelationship',
        ),
        migrations.RenameField(
            model_name='paperpersonrelationship',
            old_name='people',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='presentationpersonrelationship',
            old_name='people',
            new_name='person',
        ),
    ]
