# Generated by Django 2.2.7 on 2019-12-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191205_0154'),
        ('publication', '0011_auto_20191205_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='presentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.Person'),
        ),
        migrations.DeleteModel(
            name='PresentationPersonRelationship',
        ),
    ]
