# Generated by Django 2.2.7 on 2019-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_auto_20191205_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='date_fmt',
            field=models.CharField(choices=[('Y', 'Year'), ('YM', 'Year-Month'), ('YMD', 'Year-Month-Date')], default='YMD', max_length=8, verbose_name='Date format'),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='papertype',
            field=models.CharField(choices=[('CP', 'Conference proceeding'), ('JA', 'Journal article')], default='JA', max_length=8, verbose_name='Paper type'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='date_fmt',
            field=models.CharField(choices=[('Y', 'Year'), ('YM', 'Year-Month'), ('YMD', 'Year-Month-Date')], default='YMD', max_length=8, verbose_name='Date format'),
        ),
        migrations.AddField(
            model_name='thesispage',
            name='date_fmt',
            field=models.CharField(choices=[('Y', 'Year'), ('YM', 'Year-Month'), ('YMD', 'Year-Month-Date')], default='YMD', max_length=8),
        ),
        migrations.AddField(
            model_name='thesispage',
            name='degree',
            field=models.CharField(choices=[('PhD', 'Ph.D.'), ('MS', 'Master')], default='PhD', max_length=8, verbose_name='Academic degree'),
        ),
    ]
