# Generated by Django 2.2.7 on 2019-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_auto_20191124_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='date',
            field=models.DateField(verbose_name='Published date'),
        ),
        migrations.AlterField(
            model_name='thesispage',
            name='date',
            field=models.DateField(verbose_name='Published date'),
        ),
    ]
