# Generated by Django 2.2.7 on 2019-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_auto_20191211_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='papertype',
        ),
        migrations.RemoveField(
            model_name='paperpage',
            name='refinfo',
        ),
        migrations.AddField(
            model_name='paperpage',
            name='issue',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='page',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='volume',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
