# Generated by Django 2.2.7 on 2019-12-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('publication', '0016_auto_20191213_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='notepagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='notepersonrelationship',
            name='document',
        ),
        migrations.RemoveField(
            model_name='notepersonrelationship',
            name='note',
        ),
        migrations.RemoveField(
            model_name='notesindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NotePage',
        ),
        migrations.DeleteModel(
            name='NotePageTag',
        ),
        migrations.DeleteModel(
            name='NotePersonRelationship',
        ),
        migrations.DeleteModel(
            name='NotesIndexPage',
        ),
    ]
