# Generated by Django 2.2.7 on 2019-12-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0017_auto_20191215_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='presentation_type',
            field=models.CharField(blank=True, choices=[('INT', 'International conference'), ('DOM', 'Domestic conference'), ('SEM', 'Seminar'), ('ETC', 'etc.')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publication.Category'),
        ),
        migrations.AddField(
            model_name='presentationpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publication.Category'),
        ),
    ]
